(() => {
const API='https://api.imgbb.com/1/upload', MAX=32*1024*1024;
const $=id=>document.getElementById(id);
const e={apiKey:$('apiKey'),apiStatus:$('apiStatus'),remember:$('rememberKey'),toggle:$('toggleKey'),linkType:$('linkType'),conc:$('concurrency'),drop:$('dropzone'),input:$('fileInput'),pick:$('pickFiles'),upload:$('uploadAll'),clear:$('clearAll'),queue:$('queue'),info:$('queueInfo'),result:$('resultText'),ok:$('okCount'),fail:$('failCount'),copy:$('copyAll'),copyNum:$('copyNumbered'),toast:$('toast')};
let items=[], running=false;
const saved=localStorage.getItem('imgbb_api_key')||''; if(saved){e.apiKey.value=saved;e.remember.checked=true}
function toast(t){e.toast.textContent=t;e.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.toast.classList.remove('show'),1600)}
function fmt(n){return n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB'}
function apiState(){const ok=e.apiKey.value.trim().length>8;e.apiStatus.textContent=ok?'API key siap':'API key belum diisi';e.apiStatus.classList.toggle('ready',ok);if(e.remember.checked&&ok)localStorage.setItem('imgbb_api_key',e.apiKey.value.trim());else if(!e.remember.checked)localStorage.removeItem('imgbb_api_key')}
function add(fs){[...fs].forEach(file=>{if(!file.type.startsWith('image/'))return;items.push({id:crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random(),file,preview:URL.createObjectURL(file),status:file.size>MAX?'error':'queued',error:file.size>MAX?'>32 MB':'',direct:'',viewer:''})});render()}
function link(i){return e.linkType.value==='viewer'?i.viewer:i.direct}
function render(){e.queue.innerHTML='';if(!items.length){e.queue.innerHTML='<p>Belum ada gambar.</p>';e.info.textContent='Belum ada gambar.'}else{e.info.textContent=`${items.length} gambar · urutan hasil mengikuti daftar`;items.forEach((i,n)=>{const r=document.createElement('div');r.className='item';r.innerHTML=`<img class="thumb" src="${i.preview}" alt=""><div><div class="name">${n+1}. ${i.file.name}</div><div class="sub">${fmt(i.file.size)}</div></div><div class="state ${i.status}">${i.status==='queued'?'Menunggu':i.status==='uploading'?'Uploading...':i.status==='success'?'Berhasil':i.error||'Gagal'}</div><button type="button" data-id="${i.id}">×</button>`;r.querySelector('button').onclick=()=>{if(running)return;URL.revokeObjectURL(i.preview);items=items.filter(x=>x.id!==i.id);render()};e.queue.appendChild(r)})}const oks=items.filter(i=>i.status==='success'&&link(i));e.result.value=oks.map(link).join('\n');e.ok.textContent=`${oks.length} berhasil`;e.fail.textContent=`${items.filter(i=>i.status==='error').length} gagal`;e.upload.disabled=running||!items.some(i=>i.status!=='success');e.clear.disabled=running||!items.length}
async function one(i,key){i.status='uploading';render();try{const f=new FormData();f.append('image',i.file);f.append('name',i.file.name.replace(/\.[^.]+$/,''));const res=await fetch(`${API}?key=${encodeURIComponent(key)}`,{method:'POST',body:f});const j=await res.json();if(!res.ok||!j?.success||!j?.data?.url)throw new Error(j?.error?.message||`HTTP ${res.status}`);i.direct=j.data.url;i.viewer=j.data.url_viewer||j.data.url;i.status='success'}catch(err){i.status='error';i.error=err.message||'Upload gagal'}render()}
async function pool(tasks,n){let x=0;async function w(){while(true){const k=x++;if(k>=tasks.length)return;await tasks[k]()}}await Promise.all(Array.from({length:Math.min(n,tasks.length)},w))}
async function upload(){const key=e.apiKey.value.trim();if(!key){toast('Isi API key dulu');return}running=true;render();const todo=items.filter(i=>i.status!=='success');await pool(todo.map(i=>()=>one(i,key)),Math.max(1,Math.min(5,+e.conc.value||3)));running=false;render();toast('Upload selesai')}
async function copy(numbered){const links=items.filter(i=>i.status==='success'&&link(i)).map(link);if(!links.length)return toast('Belum ada link');const t=numbered?links.map((u,i)=>`${i+1}. ${u}`).join('\n'):links.join('\n');try{await navigator.clipboard.writeText(t);toast('Link dicopy')}catch{e.result.value=t;e.result.select();toast('Tekan Ctrl+C')}}
e.pick.onclick=()=>e.input.click();e.input.onchange=()=>{add(e.input.files);e.input.value=''};e.upload.onclick=upload;e.clear.onclick=()=>{if(running)return;items.forEach(i=>URL.revokeObjectURL(i.preview));items=[];render()};e.copy.onclick=()=>copy(false);e.copyNum.onclick=()=>copy(true);e.toggle.onclick=()=>{e.apiKey.type=e.apiKey.type==='password'?'text':'password';e.toggle.textContent=e.apiKey.type==='password'?'Lihat':'Sembunyi'};e.apiKey.oninput=apiState;e.remember.onchange=apiState;e.linkType.onchange=render;['dragenter','dragover'].forEach(t=>e.drop.addEventListener(t,x=>{x.preventDefault();e.drop.classList.add('drag')}));['dragleave','drop'].forEach(t=>e.drop.addEventListener(t,x=>{x.preventDefault();e.drop.classList.remove('drag')}));e.drop.addEventListener('drop',x=>add(x.dataTransfer.files));e.drop.onclick=x=>{if(!x.target.closest('button'))e.input.click()};apiState();render();
})();